### ISSUE TITLE
W1M2 - Error installing malariagen_data

### ISSUE THREAD

**Issue by harbi811** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#148] opened 2023-05-26 14:57 UTC
![image](https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/assets/47387425/fdcf33ae-8786-4102-aaed-ceeb3cfc1874)

After launching the notebook from the website, pip is unable to resolve conflicts while installing malariagen_data

**Comment by alimanfoo** [comment] 2023-05-26 16:48
Thanks @harbi811, actually this error message can be safely ignored. It is telling us that the `panel` package requires an earlier version of `bokeh`, but we are not using `panel` at all, so everything should run fine.

I know this error message is a bit ugly but there's not much we can do about it for the time being, as `malariagen_data` requires `bokeh` 3.1 or greater. Hopefully colab will upgrade their environment soon.

**Comment by alimanfoo** [comment] 2023-05-26 16:50
Closing as duplicate of #142.

**Closed by alimanfoo** 2023-05-26 16:50 UTC
